### ISSUE TITLE
Support a rigid body element in OpenTurbine

### ISSUE THREAD

**Issue by faisal-bhuiyan** [Exawind/openturbine#154]
**Task**
We need to implement the concept of a “mass element“ in OT to model rigid body behavior. Total mass and inertia for the element will be calculated based on the provided material properties. Effectively, it should contain the mass and inertia terms in the element formulation of the beam element.

**Why**
To capture the rigid body behavior of the nacelle, hub, and any other component as necessary.

**Done means**
- [ ] A mass element class introduced
- [ ] All member functions are unit tested
- [ ] Provides validation of a rigid body behavior

**Comment by faisal-bhuiyan** [comment]
Completed elsewhere.
